# Generated by Django 2.0.1 on 2018-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20180109_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FHaveDataCount', models.CharField(max_length=30)),
                ('FOnLineCount', models.CharField(max_length=30)),
                ('FOffLineCount', models.CharField(max_length=30)),
                ('FUnCouplingCount', models.CharField(max_length=30)),
                ('FCouplingCount', models.CharField(max_length=30)),
                ('FContainerCount', models.CharField(max_length=30)),
                ('FUnContainCount', models.CharField(max_length=30)),
                ('FRunningCount', models.CharField(max_length=30)),
                ('FStopCount', models.CharField(max_length=30)),
                ('FAlarmCount', models.CharField(max_length=30)),
                ('FNoAlarmCount', models.CharField(max_length=30)),
            ],
        ),
    ]
